// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpVL-rNFZ8g7UIijVKs5IMoltEZrYabgI',
    appId: '1:694514156537:web:041c182a7b8a60d6fe3328',
    messagingSenderId: '694514156537',
    projectId: 'flutter-d2021',
    authDomain: 'flutter-d2021.firebaseapp.com',
    storageBucket: 'flutter-d2021.appspot.com',
    measurementId: 'G-B5SBTNXQRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbu1y2Ewb2XLPrKjonB3QHZx3-Z9Zq6Uc',
    appId: '1:694514156537:android:a8ec9017f085de29fe3328',
    messagingSenderId: '694514156537',
    projectId: 'flutter-d2021',
    storageBucket: 'flutter-d2021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0rrt9AVlFU2rkvOW_H-Gw5VSpdi7eDAU',
    appId: '1:694514156537:ios:6301292a9ace1abefe3328',
    messagingSenderId: '694514156537',
    projectId: 'flutter-d2021',
    storageBucket: 'flutter-d2021.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0rrt9AVlFU2rkvOW_H-Gw5VSpdi7eDAU',
    appId: '1:694514156537:ios:6301292a9ace1abefe3328',
    messagingSenderId: '694514156537',
    projectId: 'flutter-d2021',
    storageBucket: 'flutter-d2021.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
